### ISSUE TITLE
Confidence map 

### ISSUE THREAD

**Issue by Laihu08** [abdo-eldesokey/nconv#10]
hi, recently I looked into your code and got doubt on how to obtain a confidence map from the sparse depth map. Please help me to go through this doubt, Thanks in advance.

**Comment by abdo-eldesokey** [comment]
Dear Rahul,
Please check out recent paper from CVPR 2020 on estimating the input
confidence
http://openaccess.thecvf.com/content_CVPR_2020/papers/Eldesokey_Uncertainty-Aware_CNNs_for_Depth_Completion_Uncertainty_from_Beginning_to_End_CVPR_2020_paper.pdf
