### ISSUE TITLE
evaluate function

### ISSUE THREAD

**Issue by sshan-zhao** [abdo-eldesokey/nconv#2]
Hi,
Is there an error in the evaluate function in kittidepthtrainer?

outputs *= self.params['data_normalize_factor']/256
labels *= self.params['data_normalize_factor']/256

why do you divide outputs by 256? I think the output should be just multiplied by data_normmalize_factor. 

Many thanks!

**Comment by abdo-eldesokey** [comment]
Hi,
The way depth values are stored in the KITTI dataset is the depth value in meter multiplied by 256. 
So before running the evaluation metrics, the output is divided by 256 to convert it to meters.

**Comment by sshan-zhao** [comment]
> Hi,
> The way depth values are stored in the KITTI dataset is the depth value in meter multiplied by 256.
> So before running the evaluation metrics, the output is divided by 256 to convert it to meters.

Got it!
Thank you so much!
