### ISSUE TITLE
about  pos_fn

### ISSUE THREAD

**Issue by longyangqi** [abdo-eldesokey/nconv#3]
Hi, 
I have a question about the EnforcePos part in file ncon.py.
Why do you choose to use a softplus function as a forward_pre_hook, instead of just use softplus in forward function?
My understanding is that, after lots of training iteration, the forward_pre_hook(softplus) will work on weights multiple times, which makes W = softplus(••••••softplus(W)) ? (althouth you set the beta=10, very close to RELU? it will be almost an identity map when W > 0?)  And for last training iteration, after the backward optimization, we do not apply the softplus to weights. (Which I may think that the weights are already converged?) 
But I am still confused about that...  
Can we just simply apply softplus in forward function, for both train and eval phase?
Many thanks!

**Comment by abdo-eldesokey** [comment]
Hi,
Yes, applying the non-negativity constraint directly at the beginning of forward path is the same as using a pre_forward_hook. The reason why I implemented it this way is yo mimic an official PyTorch implementation for weight_norm. 
The choice of beta=10 was found to achieve best results. Please see the paper https://arxiv.org/abs/1811.01791.

**Comment by longyangqi** [comment]
> Hi,
> Yes, applying the non-negativity constraint directly at the beginning of forward path is the same as using a pre_forward_hook. The reason why I implemented it this way is yo mimic an official PyTorch implementation for weight_norm.
> The choice of beta=10 was found to achieve best results. Please see the paper https://arxiv.org/abs/1811.01791.

Got it!
Thank you!
