### ISSUE TITLE
AAbout Normalized Convolution 

### ISSUE THREAD

**Issue by JUGGHM** [abdo-eldesokey/nconv#7]
Hi, Abdelrahman!
I notice that in normalized convolution the basis is set to only one basis constant function f(x)=1. I wonder why we don't have 2 or more basis functions and what would happen than. I would be grateful if you would like to share your view on the basis setting.

**Comment by abdo-eldesokey** [comment]
Hi JUGGHM,
Thank you for your question.
In this case, the normalized convolution formulation will become more nasty and I will include matrix inversion for each pixel in the image.
If you look at equation 3 in [the paper](https://arxiv.org/pdf/1811.01791.pdf), you can see that if you have more than 1 basis, you will add this in the columns of matrix B. Then you will need to estimate the coordinates r for each pixel in the image with respect to this basis.
I hope this answers your qeustion.

**Comment by JUGGHM** [comment]
Thanks for your sincere answer! I have found a easy way to understand: write down the expressions for conv (on 1d), than normalized conv, and than normalized conv with confidence. Finally I find that B=1 basis vector is actually enough for general convolution operations, and that we don't need two or more basis vectors in B.

> Hi JUGGHM,
> Thank you for your question.
> In this case, the normalized convolution formulation will become more nasty and I will include matrix inversion for each pixel in the image.
> If you look at equation 3 in the paper, you can see that if you have more than 1 basis, you will add this in the columns of matrix B. Then you will need to estimate the coordinates r for each pixel in the image with respect to this basis.
> I hope this answers your qeustion.
