### ISSUE TITLE
Bug when try LiDAR only 

### ISSUE THREAD

**Issue by placeforyiming** [abdo-eldesokey/nconv#9]
This is the exp I use :  exp_unguided_depth
But got this:

TypeError: __init__() missing 1 required positional argument: 'padding_mode'

Could you help us figure it out? 

The demo works very well when I choose -exp exp_guided_nconv_cnn_l2

**Comment by abdo-eldesokey** [comment]
`padding_mode` was added in recent version of pytroch. You can set it to 'zeros' and the code should work.

**Comment by placeforyiming** [comment]
OK, thank you!
